import pathlib


PATH = str(pathlib.Path(__file__).parent)

HOME_URL = "https://www.timeform.com/horse-racing/racecards"


RACE_TYPE_NAMES = {
    0: ('blank',),
    1: ('Amateur',),
    2: ('Claiming',),
    3: ('Beginners',),
    4: ('Handicap',),
    5: ('Juvenile',),
    6: ('Listed',),
    7: ('Maiden',),
    8: ('Mares',),
    9: ('Novice',),
    10: ('Selling',),
    11: ('Stakes',),
    12: ('Amateur', 'Handicap'),
    13: ('Apprentice', 'Handicap'),
    14: ('Auction', 'Stakes'),
    15: ('Auctions', 'Beginners'),
    16: ('Claiming', 'Handicap'),
    17: ('Claiming', 'Stakes'),
    18: ('Claims', 'Handicap'),
    19: ('Classified', 'Stakes'),
    20: ('Conditional', 'Handicap'),
    21: ('Conditional', 'Selling'),
    22: ('Conditions', 'Stakes'),
    23: ('Fillies', 'Handicap'),
    24: ('Fillies', 'Juvenile'),
    25: ('Fillies', 'Maiden'),
    26: ('Grade', '1'),
    27: ('Juvenile', 'Handicap'),
    28: ('Maiden', 'Auction'),
    29: ('Maiden', 'Handicap'),
    30: ('Maiden', 'Juvenile'),
    31: ('Maiden', 'Stakes'),
    32: ('Mares', 'Handicap'),
    33: ('Mares', 'Maiden'),
    34: ('Mares', 'Novices'),
    35: ('Median', 'Auction'),
    36: ('Novice', 'Auction'),
    37: ('Novice', 'Handicap'),
    38: ('Novice', 'Mares'),
    39: ('Novice', 'Mares'),
    40: ('Novice', 'Stakes'),
    41: ('Nursery', 'Handicap'),
    42: ('Selling', 'Handicap'),
    43: ('Selling', 'Stakes'),
    44: ('Stakes', 'Fillies'),
    45: ('Stakes', 'Handicap'),
    46: ('Apprentice', 'Classified', 'Stakes'),
    47: ('Claiming', 'Classified', 'Stakes'),
    48: ('Conditional', 'Maiden', 'Handicap'),
    49: ('Conditional', 'Mares', 'Handicap'),
    50: ('Conditional', 'Selling', 'Handicap'),
    51: ('Conditional', 'Veterans', 'Handicap'),
    52: ('Fillies', 'Conditions', 'Stakes'),
    53: ('Fillies', 'Juvenile', 'Maiden'),
    54: ('Fillies', 'Novice', 'Stakes'),
    55: ('Fillies', 'Nursery', 'Handicap'),
    56: ('Maiden', 'Auction', 'Stakes'),
    57: ('Maiden', 'Fillies', 'Stakes'),
    58: ('Mares', 'Conditional', 'Handicap'),
    59: ('Mares', 'Novice', 'Selling'),
    60: ('Mares', 'Novices', 'Handicap'),
    61: ('Median', 'Auction', 'Maiden'),
    62: ('Novice', 'Auction', 'Stakes'),
    63: ('Novice', 'Fillies', 'Stakes'),
    64: ('Novice', 'Median', 'Auction'),
    65: ('Restricted', 'Maiden', 'Stakes'),
    66: ('Restricted', 'Novice', 'Stakes'),
    67: ('Stakes', 'Fillies', 'Mares'),
    68: ('Novice', 'Restricted', 'Fillies', 'Stakes'),
    69: ('Maiden', 'Median', 'Auction', 'Stakes'),
    70: ('Median', 'Auction', 'Maiden', 'Stakes'),
    71: ('Median', 'Auction', 'Fillies', 'Maiden'),
    72: ('Novice', 'Median', 'Auction', 'Stakes'),
    73: ('Fillies', 'Novice', 'Median', 'Auction', 'Stakes'),
}


HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-US,en;q=0.5",
    "Cache-Control": "max-age=0",
    "Connection": "keep-alive",
    "Host": "www.timeform.com",
    "Referer": "https://www.timeform.com/",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "TE": "trailers",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Chrome/51.0.2704.103 (X11; Linux x86_64, KHTML, like Gecko)",
}


GENERAL_XLSX_COLUMNS = [
    "Date",
    "Time",
    "#",
    "Track",
    "Distance",
    "RaceType",
    "Code",
    "Runners",
    "Horse Name",
    "Jokey",
    "Trainer",
    "Horse Age",
    "Horse Weight",
    "Position",
    "Tips",
    "Tips Rating",
    "High",
    "Low",
    "BSP",
    "BPSP",
    "Winner High",
    "Winner BSP"
]
